Added Testing - Added Coverage Report - Added Complexity Report - Fixed Husky Sequence

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,24 +2,38 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo 'Husky has been initiated..'
+echo 'Checking Server Side Configurations.'
 
 # Check Prettier standards
-npm run lint:fix:all ||
+npm run --prefix server format:lint:fix ||
 (
         echo 'Due to Some ESLint Errors, Commit Has Been Stopped! 
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
         false; 
 )
 
+npm run --prefix server test || 
+(
+    echo 'Test Passed Successfully!'
+    true;
+)
+
 # Generate Complexity Report!
 npm run --prefix server complexity || (
     echo 'Report Generated. Please check the updated ./server/complexity-report.md'
+    echo 'There is no threshold limit on complexity but you may set one.'
     true;
 )
 
 # If everything passes... Now we can commit
-echo 'There is no threshold limit on complexity but you may set one.'
+echo 'Checking Client Side Configurations.'
+
+npm run --prefix client lint:fix ||
+(
+        echo 'Due to Some ESLint Errors, Commit Has Been Stopped! 
+                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+        false; 
+)
 
 git add .
 
